### ISSUE TITLE
Cannot work with accounts-password side by side

### ISSUE THREAD

**Issue by gaykan** [okland/accounts-phone#19]
When used with accounts-password, login using  loginWithPassword as an alternative does not work.
Using Angular-Meteor 1.3.2 with Meteor-client-side.

I think, many should prefer both login methods as an option for user.

**I get following message on server side**

> Exception while invoking method 'login' Error: Match error: Match error: Unknown key in field email in field user.email
> I20151231-10:21:01.508(2)?     at check (packages/check/match.js:33:1)
> I20151231-10:21:01.508(2)?     at [object Object].Accounts.registerLoginHandler.check.user (packages/okland_accounts-phone/packages/okland_accounts-phone.js:274:1)
> I20151231-10:21:01.509(2)?     at accounts_server.js:462:32
> I20151231-10:21:01.509(2)?     at tryLoginMethod (accounts_server.js:239:14)
> I20151231-10:21:01.510(2)?     at AccountsServer.Ap._runLoginHandlers (accounts_server.js:459:18)
> I20151231-10:21:01.510(2)?     at [object Object].methods.login (accounts_server.js:522:27)
> I20151231-10:21:01.510(2)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
> I20151231-10:21:01.510(2)?     at livedata_server.js:708:19
> I20151231-10:21:01.511(2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
> I20151231-10:21:01.511(2)?     at livedata_server.js:706:40
> I20151231-10:21:01.512(2)? Sanitized and reported to the client as: Match failed [400]
> I20151231-10:21:01.512(2)? 

**On the client side**

> > _Error: string.charCodeAt is not a function. (In 'string.charCodeAt(n)', 'string.charCodeAt' is undefined)
> > Utf8Encode@http://localhost:8100/lib/accounts-password-client-side.bundle.min.js:1:2442
> > SHA256@http://localhost:8100/lib/accounts-password-client-side.bundle.min.js:1:2985
> > _hashPassword@http://localhost:8100/lib/accounts-password-client-side.bundle.min.js:1:27418
> > loginWithPassword@http://localhost:8100/lib/accounts-password-client-side.bundle.min.js:1:27073
> > http://localhost:8100/lib/angular-meteor-1.3.2/dist/angular-meteor.bundle.js:10912:24_

**Comment by ChenLi0830** [comment]
+1

**Comment by s4admin** [comment]
dup of this issue:  Meteor.loginWithPhoneAndPassword fails

Is this package being maintained?

**Comment by ChenLi0830** [comment]
It doesn't seem to be.

**Comment by leonardobazico** [comment]
Any updates about that?

**Comment by erperejildo** [comment]
+1
