### ISSUE TITLE
Meteor.loginWithPhoneAndPassword fails

### ISSUE THREAD

**Issue by byrne-yan** [okland/accounts-phone#5]
I20150827-20:05:10.205(8)? Exception while invoking method 'login' Error: Match error: Unknown key in field phone in field user.phone
I20150827-20:05:10.205(8)?     at packages/check/match.js:299:1
I20150827-20:05:10.205(8)?     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
I20150827-20:05:10.205(8)?     at checkSubtree (packages/check/match.js:290:1)
I20150827-20:05:10.206(8)?     at check (packages/check/match.js:32:1)
I20150827-20:05:10.206(8)?     at [object Object].condition (packages/accounts-password/password_server.js:111:1)
I20150827-20:05:10.206(8)?     at checkSubtree (packages/check/match.js:220:1)
I20150827-20:05:10.206(8)?     at packages/check/match.js:293:1
I20150827-20:05:10.206(8)?     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
I20150827-20:05:10.206(8)?     at checkSubtree (packages/check/match.js:290:1)
I20150827-20:05:10.207(8)?     at check (packages/check/match.js:32:1)
I20150827-20:05:10.207(8)?     at [object Object].Accounts.registerLoginHandler.check.user (packages/accounts-password/password_server.js:144:1)
I20150827-20:05:10.207(8)?     at packages/accounts-base/accounts_server.js:358:1
I20150827-20:05:10.207(8)?     at tryLoginMethod (packages/accounts-base/accounts_server.js:161:1)
I20150827-20:05:10.207(8)?     at runLoginHandlers (packages/accounts-base/accounts_server.js:355:1)
I20150827-20:05:10.207(8)?     at [object Object].Meteor.methods.login (packages/accounts-base/accounts_server.js:409:1)
I20150827-20:05:10.208(8)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)

In file password_server.js of package accounts-password:
only one of id,username and email allowed!

**Comment by byrne-yan** [comment]
This issue was caused by LoginHandler registered by Accounts-password package.

**Comment by byrne-yan** [comment]
Another property name like 'phonepassword' instead of 'password' need be used to work with accoutns-password package in a same project.

**Comment by mayinhosa** [comment]
+1
having the same issue.

@byrne-yan how exactly did you work around this?

**Comment by dennishu001** [comment]
It seems to have something to do with the order the login service is registered. I added account-password as a root package, and downloaded accounts-phone to 
 


    On Monday, November 23, 2015 10:29 PM, mayinhosa <notifications@github.com> wrote:
 

 +1
having the same issue.@byrne-yan how exactly did you work around this?—

**Comment by arvi** [comment]
I'm having the same issue. I followed https://meteorhacks.com/extending-meteor-accounts tutorial for custom authentication then did `meteor add accounts-password` package since I want to use Accounts.createUser instead of the normal mongodb insert.

```bash
I20151127-16:01:52.001(8)? Exception while invoking method 'login' Error: Match error: Unknown key in field admin
I20151127-16:01:52.002(8)?     at check (packages/check/match.js:33:1)
I20151127-16:01:52.002(8)?     at [object Object].Accounts.registerLoginHandler.check.user (password_server.js:248:3)
I20151127-16:01:52.002(8)?     at accounts_server.js:462:32
I20151127-16:01:52.002(8)?     at tryLoginMethod (accounts_server.js:239:14)
I20151127-16:01:52.002(8)?     at AccountsServer.Ap._runLoginHandlers (accounts_server.js:459:18)
I20151127-16:01:52.002(8)?     at [object Object].methods.login (accounts_server.js:522:27)
I20151127-16:01:52.003(8)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20151127-16:01:52.003(8)?     at livedata_server.js:708:19
I20151127-16:01:52.003(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151127-16:01:52.003(8)?     at livedata_server.js:706:40
I20151127-16:01:52.003(8)? Sanitized and reported to the client as: Match failed [400]
```

I found out it's because we're passing a string instead of a `user` object that's being checked.
https://github.com/meteor/meteor/blob/devel/packages/accounts-password/password_server.js#L244

I tried passing an object e.g
`var loginRequest = {user: {username:'adminsample'}, password: password};`

the error went away but it seems to not reach the server's Accounts.registerHandler when I try to `console.log(loginRequest)`.

It seems the error is due to different registerHandler process done in accounts_server and password_server in the meteor codebase and that automatically the password_server's function will be used when accounts-password is added.

Hmmmmm haven't figure out how to use both accounts-ui and accounts-password with custom authentication.

Wew.

**Comment by Micjoyce** [comment]
+1
having the same issue.
@byrne-yan  how exactly did you work around this?

**Comment by Micjoyce** [comment]
@byrne-yan   How can you solve the process of sharing to me? I need you help

**Comment by byrne-yan** [comment]
@mayinhosa @Micjoyce  
Basic Idea is:
1.change to different key name when registerLoginHandler for phone to avoid conflicting with account_password. In phone_server.js:

```
Accounts.registerLoginHandler("phone", function (options) {
 -    if (!options.password || options.srp)
 +    if (!options.passwordEx || options.srp)
          return undefined; // don't handle           
      check(options, {  
          user    : userQueryValidator, 
 -        password: passwordValidator       
 +        passwordEx: passwordValidator
      });
```

2.In Meteor.loginWithPhoneAndPassword function, user's password passed in Accounts.callLoginMethod as the filed of paswordEx:

```
 +   if(selector.phone){
 +        args =
 +        {
 +            user: selector,
 +            passwordEx: Accounts._hashPassword(password)
 +        }
 +
 +    }
 +    Accounts.callLoginMethod({
 +        methodArguments: [args],
```

More details on my project:
https://github.com/byrne-yan/accounts-phone/commit/15a02a2665fd6ec3910c7c27bdf6578f8ddf7bed

**Comment by psramkumar** [comment]
any update on this issue. did any one found the fix for this issue ?

**Comment by s4admin** [comment]
I have the same issue.  Fixed by removing accounts-password, but that has other issues...

**Comment by ChenLi0830** [comment]
Tried the fix of @byrne-yan, and it worked!

To be more specific, here is what fixed the problem:
1. Add the accounts-phone as a local package. In case you are relatively new to this, [here](https://dweldon.silvrback.com/local-packages) is a pretty good article of how to do it.
2. Remove the /dist folder (or alternatively you can probably re-run the /bundle-min.sh script once you finish step3 to override the /dist folder, I didn't try it though)
3. Make the code change mentioned by @byrne-yan. The repository is forked to show the code change more clearly [here](https://github.com/ChenLi0830/accounts-phone/commit/06fed100b2bced123e4631ffcd28c1cfbf168d90)

**Comment by chylvina** [comment]
just run

```
meteor remove accounts-password
```
